# -*- coding: utf-8 -*-
"""product.pyt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmhoONh_FD_FhR9jZaCEjjqp37MXx5QZ
"""

from transformers import pipeline
import pandas as pd
#load sentiment analysis model
sentiment = pipeline("sentiment-analysis") # Corrected: Changed 'sentiment analysis' to 'sentiment-analysis'
#sample product review (you can change only this text later)
review = """the laptop starts quickly and work smoothly for daily tasks.
the screen quality is clear and good for watching videos.
battery backup is average and need charging often.
the fan makes noise when many appsare running.
overall it is a good laptop for students butnot for gaming."""
#split review into sentences
sentences = review.split(".")
pros = []
cons = []
for s in sentences:
  s = s.strip()
  if s == "":
    continue
  result = sentiment(s)[0]
  if result ["label"] == "POSITIVE":
    pros.append(s)
  elif result ["label"] == "NEGATIVE":
    cons.append(s)

#take only 2pros & 2cons
pros = pros[:2]
cons = cons[:2]
#create table
df = pd.DataFrame({"pros":pros,"cons":cons})
df