# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZZ3f4mwRNlWQLfstM2Q47qhMG6_45pa
"""



!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
#lode the mode1
model = SentenceTransformer('all-MiniLM-L6-v2')
#take input from user
text1 = input('Enter text 1: ')
text2 = input('Enter text 2: ')
#convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similaritys
similarity=util.cos_sim(embedding1,embedding2)
#show result
print("\n similaity score: ",round(float(similarity),2))
if similarity>0.75 :
  print("similarity score: HIGH ")
elif similarity>0.4:
  print("similarity score: MEDIUM")
else:
    print("similarity score: low")